version: '3.8'

services:
  api:
    image: DOCKER_DEPLOY_APP_IMAGE
    container_name: rl-idle_api
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    ports:
      - '3000:3000'

  db:
    image: postgres:latest
    container_name: rl-idle_db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    ports:
      - '5432:5432'

  redis:
    restart: unless-stopped
    container_name: rl-idle_redis
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  redis-data:
